/**
 * March Networks
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Unauthorized, invalid session.
 */
export interface AuthControllerCreateUser401Response { 
    statusCode: number;
    message: string;
    error?: string;
}

