/**
 * March Networks
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserEntity } from './userEntity';


export interface AuthResponseDto { 
    /**
     * The User Entity
     */
    user: UserEntity;
    /**
     * The token which should be used for future requests (Bearer Authentication)
     */
    token: string;
}

