/**
 * March Networks
 * Project One API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Channel2Entity { 
    /**
     * The I.D of the channel.
     */
    id: string;
    /**
     * The I.D of the tenant.
     */
    deviceId: string;
    /**
     * The name of the channel.
     */
    name: string;
    /**
     * The date the entity was created.
     */
    createdAt: string;
    /**
     * The last time the entity was updated.
     */
    updatedAt: string;
}

