/**
 * March Networks
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DeviceEntity } from './deviceEntity';


export interface ChannelEntity { 
    /**
     * The I.D of the channel.
     */
    id: string;
    /**
     * The name of the channel.
     */
    name: string;
    /**
     * The associated device.
     */
    device: DeviceEntity;
}

