/**
 * March Networks
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ConfirmEmailRequestDto { 
    /**
     * The desired password.
     */
    password: string;
    /**
     * The I.D of the user.
     */
    id: string;
    /**
     * The generated token to authenticate the confirm email request.
     */
    token: string;
}

