/**
 * March Networks
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LicenseEntity } from './licenseEntity';
import { DefaultRolesResponseDto } from './defaultRolesResponseDto';


export interface CreateTenantWithDefaultsResponseDto { 
    /**
     * The created tenant I.D
     */
    id: string;
    /**
     * The default role I.Ds for the newly created tenant
     */
    roles: DefaultRolesResponseDto;
    /**
     * The list of licenses for the newly created tenant
     */
    licenses: Array<LicenseEntity>;
}

