/**
 * March Networks
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateChannelRequestDto { 
    /**
     * The name of the device or channel.
     */
    name: string;
    /**
     * The I.D of the device to add the channel too.
     */
    deviceId: string;
}

