/**
 * March Networks
 * Project One API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateTenantRequestLicenseDto } from './createTenantRequestLicenseDto';


export interface CreateTenantWithDefaultsRequestDto { 
    /**
     * The name to use for the tenant
     */
    name: string;
    /**
     * The email of the tenant.
     */
    email: string;
    /**
     * The EV license params.
     */
    license?: CreateTenantRequestLicenseDto;
}

