/**
 * March Networks
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateTenantRequestDto { 
    /**
     * The name to use for the tenant
     */
    name: string;
    /**
     * The email of the tenant.
     */
    email: string;
}

