/**
 * March Networks
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateUserRequestDto { 
    /**
     * The username for the user.
     */
    username: string;
    /**
     * The email of the user.
     */
    email: string;
    /**
     * The I.D of the role which should be assigned to the user
     */
    roleId: string;
}

