/**
 * March Networks
 * Project One API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DefaultRolesDto } from './defaultRolesDto';


export interface CreateTenantWithRolesResponseDto { 
    /**
     * The created tenant I.D
     */
    id: string;
    /**
     * The default role I.Ds for the newly created tenant
     */
    roles: DefaultRolesDto;
}

