/**
 * March Networks
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EvLicenseMetadataDto } from './evLicenseMetadataDto';


export interface CreateEvLicenseRequestDto { 
    /**
     * The I.D of the tenant.
     */
    tenantId: string;
    /**
     * The date at which the license expires
     */
    expiresAt?: string;
    /**
     * The date at which the license was issued at
     */
    issuedAt?: string;
    /**
     * The required metadata for the license
     */
    metadata?: EvLicenseMetadataDto;
}

