/**
 * March Networks
 * Project One API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DefaultRolesDto { 
    /**
     * The admin role I.D
     */
    adminRoleId: string;
    /**
     * The limited role I.D
     */
    limitedRoleId: string;
    /**
     * The some role I.D
     */
    someRoleId: string;
}

