/**
 * March Networks
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DefaultRolesResponseDto { 
    /**
     * The admin role I.D
     */
    adminRoleId: string;
    /**
     * The limited role I.D
     */
    limitedRoleId: string;
    /**
     * The some role I.D
     */
    someRoleId: string;
}

