/**
 * March Networks
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DeviceEntity { 
    /**
     * The I.D of the device.
     */
    id: string;
    /**
     * The name of the device.
     */
    name: string;
}

