/**
 * March Networks
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Device2Entity { 
    /**
     * The I.D of the device.
     */
    id: string;
    /**
     * The I.D of the tenant.
     */
    tenantId: string;
    /**
     * The name of the device.
     */
    name: string;
    /**
     * The date the device was created.
     */
    createdAt: string;
    /**
     * The last time the device was updated.
     */
    updatedAt: string;
}

