/**
 * March Networks
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EvLicenseMetadataDto { 
    /**
     * The amount a tenant can download in GB
     */
    downloadLimitGB: number;
    /**
     * The amount a tenant can store in GB
     */
    storageLimitGB: number;
}

