/**
 * March Networks
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The name of model.
 */
export enum GenerativeModelEnum {
    AmazonTitanEmbedImageV1 = 'AmazonTitanEmbedImageV1',
    GeminiOnePointFivePro = 'GeminiOnePointFivePro'
}

