/**
 * March Networks
 * Project One API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ImageEntity { 
    /**
     * The I.D of the tenant.
     */
    tenantId: string;
    /**
     * The I.D of the role.
     */
    id: string;
    /**
     * The name of the file.
     */
    fileName: string;
    /**
     * The name of the file.
     */
    originalName: string;
    /**
     * The content of the vectorized file.
     */
    content: string;
    /**
     * The content of the vectorized file.
     */
    createdAt: string;
}

