/**
 * March Networks
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SearchQueryEntity } from './searchQueryEntity';


export interface IntelligentRetrievalEventEntity { 
    /**
     * The I.D of the Intelligent Retrieval Event.
     */
    id: string;
    /**
     * The name of the event.
     */
    name: string;
    /**
     * The minimum similarity score threshold.
     */
    similarityScore: number;
    /**
     * The time the event was created.
     */
    createdAt: string;
    /**
     * The last time the event was updated.
     */
    updatedAt: string;
    /**
     * The related search query.
     */
    searchQuery: SearchQueryEntity;
}

