/**
 * March Networks
 * Project One API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LicensedProductEntity { 
    /**
     * The I.D of the license.
     */
    id: string;
    /**
     * The name of the license.
     */
    name: string;
    /**
     * The date the license was created.
     */
    createdAt: string;
}

