/**
 * March Networks
 * Project One API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoginRequestDto { 
    /**
     * The password for the user.
     */
    password: string;
    /**
     * The name of the tenant.
     */
    tenantName: string;
    /**
     * The email or username of the user who forgot their password.
     */
    emailOrUsername: string;
}

