/**
 * March Networks
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TenantEntity } from './tenantEntity';


export interface PaginatedResponseOfTenantEntity { 
    results: Array<TenantEntity>;
    total: number;
    take: number;
    skip: number;
}

