/**
 * March Networks
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IntelligentRetrievalEventEntity } from './intelligentRetrievalEventEntity';


export interface PaginatedResponseOfIntelligentRetrievalEventEntity { 
    results: Array<IntelligentRetrievalEventEntity>;
    total: number;
    take: number;
    skip: number;
}

