/**
 * March Networks
 * Project One API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserEntity } from './userEntity';


export interface PaginatedResponseOfUserEntity { 
    results: Array<UserEntity>;
    total: number;
    take: number;
    skip: number;
}

