/**
 * March Networks
 * Project One API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleEntity } from './roleEntity';


export interface PaginatedResponseOfRoleEntity { 
    results: Array<RoleEntity>;
    total: number;
    take: number;
    skip: number;
}

