/**
 * March Networks
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChannelImageWithDistanceEntity } from './channelImageWithDistanceEntity';


export interface PaginatedResponseOfChannelImageWithDistanceEntity { 
    results: Array<ChannelImageWithDistanceEntity>;
    total: number;
    take: number;
    skip: number;
}

