/**
 * March Networks
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RoleControllerDelete400Response { 
    statusCode: number;
    message: string;
    errorCode: string;
    timestamp: string;
}

