/**
 * March Networks
 * Project One API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PermissionEntity } from './permissionEntity';


export interface RoleEntity { 
    /**
     * The I.D of the role
     */
    id: string;
    /**
     * The name of the role
     */
    name: string;
    /**
     * The permissions associated to the role
     */
    permissions: Array<PermissionEntity>;
}

