/**
 * March Networks
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SearchRequestDto { 
    /**
     * The query to search for
     */
    query: string;
    /**
     * The device I.D
     */
    deviceId?: string;
    /**
     * The channel I.D
     */
    channelId?: string;
    /**
     * The maximum amount of desired results to return
     */
    resultsToReturn?: number;
}

