/**
 * March Networks
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SearchQueryEntity { 
    /**
     * The I.D of the search query.
     */
    id: string;
    /**
     * The I.D of the channel.
     */
    lowerCaseQuery: string | null;
    /**
     * The name of the file.
     */
    originalQuery: string | null;
    /**
     * The name of the file.
     */
    fileName: string | null;
}

