/**
 * March Networks
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SimpleResponseDto { 
    /**
     * Was the response successful (true) or unsuccessful (false)
     */
    success: boolean;
}

