/**
 * March Networks
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GenerativeModelEnum } from './generativeModelEnum';


export interface UpdateSettingsRequestDto { 
    generativeModel: GenerativeModelEnum;
}



