/**
 * March Networks
 * Project One API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleEntity } from './roleEntity';


export interface UserEntity { 
    /**
     * The user\'s I.D
     */
    id: string;
    /**
     * The user\'s public I.D
     */
    publicId: string;
    /**
     * The user\'s email address
     */
    email: string;
    /**
     * The user\'s email address
     */
    username: string;
    /**
     * The I.D of the tenant
     */
    tenantId: string;
    /**
     * Is the user currently enabled
     */
    enabled: boolean;
    /**
     * Has the user verified their email address
     */
    verifiedEmail: boolean;
    /**
     * The Role attached to this User
     */
    role: RoleEntity;
}

